#pragma once
#include <Windows.h>

static class ConsoleConstants {
public:
	WORD const FOREGROUND_COLOR_RED = FOREGROUND_RED;
	WORD const FOREGROUND_COLOR_GREEN = FOREGROUND_GREEN;
	WORD const FOREGROUND_COLOR_BLUE = FOREGROUND_BLUE;
	WORD const FOREGROUND_COLOR_YELLOW = FOREGROUND_RED | FOREGROUND_GREEN;
	WORD const FOREGROUND_COLOR_WHITE = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE;
	WORD const FOREGROUND_BLACK = 0;

	WORD const BACKGROUND_COLOR_RED = BACKGROUND_RED;
	WORD const BACKGROUND_COLOR_GREEN = BACKGROUND_GREEN;
	WORD const BACKGROUND_COLOR_BLUE = BACKGROUND_BLUE;
	WORD const BACKGROUND_COLOR_YELLOW = BACKGROUND_RED | BACKGROUND_GREEN;
	WORD const BACKGROUND_COLOR_WHITE = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE;
	WORD const BACKGROUND_BLACK = 0;
};

